### ISSUE TITLE
Don't use Java

### ISSUE THREAD

**Issue by kegelsknight** [J0B10/JMacros#1]
Don't use Java for makro creating but rather a runtime independent language.

**Comment by J0B10** [comment]
😂 I get your point but no.

I picked java because of its spread and simplicity. I want the api to be as easy to use as possible  and as java is the beginner language it is perfect for that.

Also you know that the JVM is where I feel at home so my choice might also be a bit irrational.

I know this comes with a lot of downsides but I'm willing to sacrifice them.
